In [1]:
print("Hello World")

Hello World


In [2]:
print("sravani nimmagadda")

sravani nimmagadda


In [1]:
a=10
print(a)

10


In [2]:
x=10
x

10

In [4]:
x,y=10,4
y

4

In [2]:
a=9
b=2
a%b

1

In [3]:
7%2

1

In [4]:
3//5


0

In [5]:
5//3

1

In [6]:
15//30

0

In [7]:
-15//30

-1

In [1]:
str=input("hello")
print(str)

helloworld
world


In [2]:
a=int(input("a"))

a1


In [1]:
#shift+tab
import numpy as np
np.arange(3,6)

array([3, 4, 5])

In [2]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.zeros(100,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
np.array([1,3,5,7,10])

array([ 1,  3,  5,  7, 10])

In [10]:
np.random.rand(2,4)

array([[0.49330442, 0.39785518, 0.66907574, 0.24986827],
       [0.33405897, 0.40003923, 0.1728433 , 0.88774595]])

In [11]:
np.random.randn(1,4)

array([[ 0.95036091,  1.36767796, -0.31748225, -0.70131773]])

In [16]:
np.random.randint(1,5)

3

In [3]:
my_set={2,5,5,1,3,7,10.5,111,'hi','data'}
my_set

{1, 10.5, 111, 2, 3, 5, 7, 'data', 'hi'}

### set doesnot allow duplicates
### arrange acc to first digit
### cant specify index

In [14]:
my_set.update([99])
my_set

{1, 10.5, 111, 2, 3, 7, 99, 'data'}

In [15]:
my_set.remove(3)

In [16]:
my_set

{1, 10.5, 111, 2, 7, 99, 'data'}

In [18]:
my_set=set("dataScience")
my_set

{'S', 'a', 'c', 'd', 'e', 'i', 'n', 't'}

In [22]:
my_set.pop()


'i'

In [23]:
a={1,2,3,4,5}
b={3,4,5,6,7}
print(a|b)   ### union

{1, 2, 3, 4, 5, 6, 7}


In [26]:
a.union(b)
b.union(a)

{1, 2, 3, 4, 5, 6, 7}

In [27]:
a&b #intersection

{3, 4, 5}

In [28]:
a.intersection(b)

{3, 4, 5}

In [29]:
a-b

{1, 2}

In [33]:
a.difference(b)

{1, 2}

In [34]:
a^b

{1, 2, 6, 7}

In [35]:
a.symmetric_difference(b)

{1, 2, 6, 7}

# Dictionary

In [37]:
my_dict={1:'first',2:'second',3:'third'}
my_dict

{1: 'first', 2: 'second', 3: 'third'}

#####  keys unique and values can be duplicated

In [38]:
my_dict={1:'first',2:"hi",2:'second',3:'third'}
my_dict

{1: 'first', 2: 'second', 3: 'third'}

#### keys cant be retrived using values but values can be retrived

In [39]:
my_dict["third"]
my_dict

KeyError: 'third'

In [40]:
my_dict[5]='hi'
my_dict

{1: 'first', 2: 'second', 3: 'third', 5: 'hi'}

In [41]:
my_dict.pop(5)
my_dict

{1: 'first', 2: 'second', 3: 'third'}

In [45]:
set={1,2,3,4}
#set.clear()
set

{1, 2, 3, 4}

In [51]:
b=set.copy()
b

{1, 2, 3, 4}

In [48]:
my_dict.keys()


dict_keys([1, 2, 3])

In [49]:
my_dict.values()

dict_values(['first', 'second', 'third'])

In [50]:
my_dict.items()

dict_items([(1, 'first'), (2, 'second'), (3, 'third')])